name: Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build (optional)
      - name: Build app
        run: npm run build --if-present

      # Azure Login (HARDCODED)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ae7ad2c1-261b-4fa9-a255-3806d71bddbb
          tenant-id: 2c8ec8cc-e229-4568-b011-fbb60ed4385c
          subscription-id: b74e302a-6b7a-47a5-ad64-fa0a700043e7
          allow-no-subscriptions: false

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mono-app-ser
          package: .
